### ISSUE TITLE
Sound up from function keyboard not working

### ISSUE THREAD

**Issue by metal3d** [decathorpe/elementary-nightly-rpms#38] opened 2016-12-04 13:54 UTC
Some shortcuts seems to be broken - one that is relevant is the function key + volume up that does ntohing while volume down and mute are ok.

PS: I see other issues there for Super+Space, but I really thing we should find a solution for that
PS: Really happy to use Pantheon on Fedora !

**Comment by decathorpe** [comment] 2016-12-05 17:39
I'm not sure what the problem is here, and I cannot reproduce the issue on my system (function key + volume up works on my keyboard). I guess the keyboard combination works in GNOME? (Those settings are shared as far as I know).

**Comment by metal3d** [comment] 2016-12-06 22:48
Yes that works on Gnome 3, I really don't understand what happends.

Maybe I will retry with your nightly builds...

I let this issue open the time I make some other tests.

PS: Super+S or Super+Space is not working too, I wonder if there is a link with that issue

**Comment by decathorpe** [comment] 2016-12-07 10:43
What are Super+S and Super+Space supposed to do on elementaryOS?

**Comment by metal3d** [comment] 2016-12-07 10:48
Theorically that shoud open a vommand launcher. As Gnome does by alt+F2.
If you check settings, keyboard, shortcuts, you'll see that super+s is bind
to launcher. But nothing appears.

Le mer. 7 déc. 2016 11:43, Fabio Valentini <notifications@github.com> a
écrit :

**Comment by decathorpe** [comment] 2016-12-07 11:01
Ah, you mean the shortcut for opening the slingshot launcher doesn't work. That bug has already been reported [here](https://github.com/decathorpe/elementary-stable-rpms/issues/4) ...

What is Super+Space supposed to do?

**Comment by decathorpe** [comment] 2017-12-31 21:58
I'm closing this issue since it's over a year old now, and the issue is probably gone (or different) by now. If it's still there or reappears, feel free to report another issue.

**Closed by decathorpe** 2017-12-31 21:58 UTC
