### ISSUE TITLE
Notifications do not respect the Sounds toggle in settings

### ISSUE THREAD

**Issue by heksesang** [decathorpe/elementary-nightly-rpms#11] opened 2016-06-23 10:12 UTC
If I disable Sounds for an app in Notification settings, there still comes a pop sound when there is a notification.

**Comment by decathorpe** [comment] 2016-06-23 13:09
Can you check if this also happens on an up-to-date elementary OS Loki (for example in a VM)?

**Comment by decathorpe** [comment] 2017-01-20 10:55
Does this issue affect only programs which generate their own notification sounds? If so, the setting can't do anything about that.

**Comment by decathorpe** [comment] 2017-12-31 21:58
I'm closing this issue since it's over a year old now (and there was never any response from the reporter) and the issue is probably gone (or different) by now. If it's still there or reappears, feel free to report another issue.

**Closed by decathorpe** 2017-12-31 21:58 UTC
